# This file was generated by GoReleaser. DO NOT EDIT.
cask "landfall" do
  version "0.7.9"

  on_macos do
    on_arm do
      sha256 "130aa58eaad24e969fcfe0590f97409bf0b8bbfcc5361dd98b91269ae937d56d"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "616a5d55e3801eecbfe58a54fe0ddbb859299330ce2406c4c15ef13d023315da"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d791e2465739f76e010d84b821ae0fc03d8531c59d7d77459b2d7d395d3cbf46"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "187de8f771d70e1ae57d2b7b3cc0f6608afc6219cad60035afd13f82f7129a32"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_linux_amd64.tar.gz"
    end
  end

  name "landfall"
  desc "Join a Landfall war room from your terminal"
  homepage "https://github.com/landfalls-ai/landfall-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "landfall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/landfall"]
    end
  end

  # No zap stanza required
end
