# This file was generated by GoReleaser. DO NOT EDIT.
cask "landfall" do
  version "0.8.12"

  on_macos do
    on_arm do
      sha256 "88d0b01bf512e9ba0ade9fde1dcb96d2831761baa310c99193c5c5b5e1f78203"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6173151b24da7e048e8c374a4e7e7f988903c5ff4fd9162c25facf6e38c0762c"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3fe29db2922fdff2ccfd8598aa045cf2e10fd52fa6cac64df25878aa77581f3e"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d9a9ac4786a2c95b02c391c28b516fbc06fabcc7346e19bb359a042ecd1bf27"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_linux_amd64.tar.gz"
    end
  end

  name "landfall"
  desc "Join a Landfall war room from your terminal"
  homepage "https://github.com/landfalls-ai/landfall-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "landfall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/landfall"]
    end
  end

  # No zap stanza required
end
