# This file was generated by GoReleaser. DO NOT EDIT.
cask "landfall" do
  version "0.7.2"

  on_macos do
    on_arm do
      sha256 "bef167f0edaf50f9e258da535b5df99278fe38ae3a3bbf1445cc0be5fda3bc3e"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "21bc7063d326ec4b57f5c91291c747354e13fdb0105937a4cfcfab89aece7ed6"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ba23352b181ae65363316913cc0dd9d3efff1f7d26b8f052f0c38eb4b1b88038"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77ff64a3e104985853100e344f10c9ce22ced6a43c751fbf323896d1531cf3c6"
      url "https://github.com/landfalls-ai/landfall-cli/releases/download/v#{version}/landfall-cli_linux_amd64.tar.gz"
    end
  end

  name "landfall"
  desc "Join a Landfall war room from your terminal"
  homepage "https://github.com/landfalls-ai/landfall-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "landfall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/landfall"]
    end
  end

  # No zap stanza required
end
